services:
  mongo:
    image: mongo:7
    container_name: smoke-mongo
    ports:
      - "27017:27017"
    volumes:
      - smoke_mongo_data:/data/db

  dataservice:
    build:
      context: ./DataService
    container_name: smoke-dataservice
    environment:
      - PORT=5001
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=smoke
    depends_on:
      - mongo
    ports:
      - "5001:5001"

  
  gateway:
    build:  
      context: ./GatewayService
    container_name: smoke-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Override appsettings in container:
      - DataService__BaseUrl=http://dataservice:5001
      # Optional: ensure ASP.NET binds to container port
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - dataservice
    ports:
      - "8080:8080"


volumes:
  smoke_mongo_data:
